return "return {[\"background\"] = \"gui_elfbg.png\", " ..
	"[\"title\"] = \"Legendary Weapons\"," ..
	"[\"page_max\"] = 4, [\"text_len\"] = 1500, [\"owner\"] = \"a Dwarvish Smith\"," ..
	"[\"text\"] = \"Descriptions of the most powerful weapons in Middle-earth are contained within these pages. Recipes may be found in the Forbidden Book.\\\n\\\n" ..
	"GLAMDRING: Known as the Foe-Hammer (or Beater to the orcs), this powerful sword fires blue bolts of magic energy. These bolts travel slowly, so the sword is best used at close range.\\\n\\\n" ..
	"GIMLI'S AXE: Wielded with deft strokes by the dwarven folk, this axe does respectable damage.  However, its great power lies in the ability to make a 'vorpal' hit 5% of the time, which will completely destroy monsters by cleaving them in two!\\\n\\\n" ..
	"\\\"Speak, or I will put a dint in your hat that even a wizard will find hard to deal with!\\\"\\\n\\\n" ..
	"STING: Thus named by Bilbo Baggins after his battle in Mirkwood, this wondrous short sword grants the ability to teleport over a long distance, while cutting down enemies in its path. In addition, the sword will glow when orcs, wargs, and trolls, or evil monsters are near.  A secondary function (sneak + click) makes you very sneaky by transforming you into a mouse for one hour!  You can also toggle the transformation off by using the secondary function again.  Beware, teleporting into thin air or off a cliff can be dangerous!\\\n\\\n" ..
	"WIZARD STAFF: This magic staff allows you to project beams of light at your foes. While similar to Glamdring, the beams of light are more powerful in every respect.  The staff can also create a ring of fire around the caster (sneak + click).  Fire damages monsters not immune to fire, and does 4 damage per second to players (except those who have special items such as Dwarven armor).\\\n\\\n" ..
	"\\\"I was hard put to it indeed: such light and flame cannot have been seen on Weathertop since the war-beacons of old.\\\"\\\n\\\n" ..
	"GROND: Mighty hammer of the underworld, once wielded by Morgoth. This weapon shakes the ground and causes tremendous damage. Be careful, as Grond shows no discretion, and can easily kill its owner!  The secondary function will transform you into a Nazgul, which monsters of all kinds will ignore.  Attacking a monster will remove the form.\\\n\\\n" ..
	"HIGH ELVISH BOW: This elvish bow requires no ammunition. As the string is pulled back, an arrow of blue fire appears, which travels at a great speed. The arrow then bursts into blue flame.  Wielding this bow also grants sight like an elf (press z or the zoom key).\\\n\"}"
